//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 04:36:45 PM CEST 
//


package com.mycompany.camel.xml.savefattureesito;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.mycompany.camel.xml.savefattureesito package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SERIES_QNAME = new QName("", "__SERIE_S");
    private final static QName _DESCRIZIONEESITO_QNAME = new QName("", "DESCRIZIONE_ESITO");
    private final static QName _SOCIETA_QNAME = new QName("", "SOCIETA");
    private final static QName _DESCRIZIONEERRORE_QNAME = new QName("", "DESCRIZIONE_ERRORE");
    private final static QName _ESITO_QNAME = new QName("", "ESITO");
    private final static QName _LOTID_QNAME = new QName("", "LOT_ID");
    private final static QName _TIPOCONS_QNAME = new QName("", "TIPO_CONS");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.mycompany.camel.xml.savefattureesito
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TESTATAESITO }
     * 
     */
    public TESTATAESITO createTESTATAESITO() {
        return new TESTATAESITO();
    }

    /**
     * Create an instance of {@link ROOTESITO }
     * 
     */
    public ROOTESITO createROOTESITO() {
        return new ROOTESITO();
    }

    /**
     * Create an instance of {@link DOCUMENTIESITO }
     * 
     */
    public DOCUMENTIESITO createDOCUMENTIESITO() {
        return new DOCUMENTIESITO();
    }

    /**
     * Create an instance of {@link DOCUMENTOESITO }
     * 
     */
    public DOCUMENTOESITO createDOCUMENTOESITO() {
        return new DOCUMENTOESITO();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "__SERIE_S")
    public JAXBElement<String> createSERIES(String value) {
        return new JAXBElement<String>(_SERIES_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DESCRIZIONE_ESITO")
    public JAXBElement<String> createDESCRIZIONEESITO(String value) {
        return new JAXBElement<String>(_DESCRIZIONEESITO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SOCIETA")
    public JAXBElement<String> createSOCIETA(String value) {
        return new JAXBElement<String>(_SOCIETA_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DESCRIZIONE_ERRORE")
    public JAXBElement<String> createDESCRIZIONEERRORE(String value) {
        return new JAXBElement<String>(_DESCRIZIONEERRORE_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ESITO")
    public JAXBElement<String> createESITO(String value) {
        return new JAXBElement<String>(_ESITO_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "LOT_ID")
    public JAXBElement<String> createLOTID(String value) {
        return new JAXBElement<String>(_LOTID_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TIPO_CONS")
    public JAXBElement<String> createTIPOCONS(String value) {
        return new JAXBElement<String>(_TIPOCONS_QNAME, String.class, null, value);
    }

}
