//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 04:36:45 PM CEST 
//


package com.mycompany.camel.xml.savefattureesito;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TESTATAESITO"/>
 *         &lt;element ref="{}DOCUMENTIESITO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testataesito",
    "documentiesito"
})
@XmlRootElement(name = "ROOTESITO")
public class ROOTESITO {

    @XmlElement(name = "TESTATAESITO", required = true)
    protected TESTATAESITO testataesito;
    @XmlElement(name = "DOCUMENTIESITO", required = true)
    protected DOCUMENTIESITO documentiesito;

    /**
     * Gets the value of the testataesito property.
     * 
     * @return
     *     possible object is
     *     {@link TESTATAESITO }
     *     
     */
    public TESTATAESITO getTESTATAESITO() {
        return testataesito;
    }

    /**
     * Sets the value of the testataesito property.
     * 
     * @param value
     *     allowed object is
     *     {@link TESTATAESITO }
     *     
     */
    public void setTESTATAESITO(TESTATAESITO value) {
        this.testataesito = value;
    }

    /**
     * Gets the value of the documentiesito property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTIESITO }
     *     
     */
    public DOCUMENTIESITO getDOCUMENTIESITO() {
        return documentiesito;
    }

    /**
     * Sets the value of the documentiesito property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTIESITO }
     *     
     */
    public void setDOCUMENTIESITO(DOCUMENTIESITO value) {
        this.documentiesito = value;
    }

}
