//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 04:36:45 PM CEST 
//


package com.mycompany.camel.xml.savefattureesito;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SOCIETA"/>
 *         &lt;element ref="{}TIPO_CONS"/>
 *         &lt;element ref="{}__SERIE_S"/>
 *         &lt;element ref="{}LOT_ID"/>
 *         &lt;element ref="{}ESITO"/>
 *         &lt;element ref="{}DESCRIZIONE_ESITO"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "societa",
    "tipocons",
    "series",
    "lotid",
    "esito",
    "descrizioneesito"
})
@XmlRootElement(name = "TESTATAESITO")
public class TESTATAESITO {

    @XmlElement(name = "SOCIETA", required = true)
    protected String societa;
    @XmlElement(name = "TIPO_CONS", required = true)
    protected String tipocons;
    @XmlElement(name = "__SERIE_S", required = true)
    protected String series;
    @XmlElement(name = "LOT_ID", required = true)
    protected String lotid;
    @XmlElement(name = "ESITO", required = true)
    protected String esito;
    @XmlElement(name = "DESCRIZIONE_ESITO", required = true)
    protected String descrizioneesito;

    /**
     * Gets the value of the societa property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSOCIETA() {
        return societa;
    }

    /**
     * Sets the value of the societa property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSOCIETA(String value) {
        this.societa = value;
    }

    /**
     * Gets the value of the tipocons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTIPOCONS() {
        return tipocons;
    }

    /**
     * Sets the value of the tipocons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTIPOCONS(String value) {
        this.tipocons = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERIES() {
        return series;
    }

    /**
     * Sets the value of the series property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERIES(String value) {
        this.series = value;
    }

    /**
     * Gets the value of the lotid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOTID() {
        return lotid;
    }

    /**
     * Sets the value of the lotid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOTID(String value) {
        this.lotid = value;
    }

    /**
     * Gets the value of the esito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getESITO() {
        return esito;
    }

    /**
     * Sets the value of the esito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setESITO(String value) {
        this.esito = value;
    }

    /**
     * Gets the value of the descrizioneesito property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDESCRIZIONEESITO() {
        return descrizioneesito;
    }

    /**
     * Sets the value of the descrizioneesito property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDESCRIZIONEESITO(String value) {
        this.descrizioneesito = value;
    }

}
