//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 03:45:14 PM CEST 
//


package com.mycompany.camel.xml.savefatture;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}__DATA_DOCUMENTO_DT"/>
 *         &lt;element ref="{}DATA_REGISTRAZIONE"/>
 *         &lt;element ref="{}__DATA_INIZIO_NUMERAZIONE_DT"/>
 *         &lt;element ref="{}__ANNO_FISCALE_I"/>
 *         &lt;element ref="{}__SERIE_S"/>
 *         &lt;element ref="{}__NUMERO_DOCUMENTO_L"/>
 *         &lt;element ref="{}__CODICE_FISCALE_S"/>
 *         &lt;element ref="{}__PARTITA_IVA_S"/>
 *         &lt;element ref="{}CODICE_CLIENTE"/>
 *         &lt;element ref="{}__DENOMINAZIONE_S"/>
 *         &lt;element ref="{}TOTALE_IMPORTO_D"/>
 *         &lt;element ref="{}NUMERO_DOC_RIF"/>
 *         &lt;element ref="{}FILE_ID"/>
 *         &lt;element ref="{}LOT_ID"/>
 *         &lt;element ref="{}DOC_HASH"/>
 *         &lt;element ref="{}FILE_NAME"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datadocumentodt",
    "dataregistrazione",
    "datainizionumerazionedt",
    "annofiscalei",
    "series",
    "numerodocumentol",
    "codicefiscales",
    "partitaivas",
    "codicecliente",
    "denominaziones",
    "totaleimportod",
    "numerodocrif",
    "fileid",
    "lotid",
    "dochash",
    "filename"
})
@XmlRootElement(name = "DOCUMENTO")
public class DOCUMENTO {

    @XmlElement(name = "__DATA_DOCUMENTO_DT", required = true)
    protected String datadocumentodt;
    @XmlElement(name = "DATA_REGISTRAZIONE", required = true)
    protected String dataregistrazione;
    @XmlElement(name = "__DATA_INIZIO_NUMERAZIONE_DT", required = true)
    protected String datainizionumerazionedt;
    @XmlElement(name = "__ANNO_FISCALE_I", required = true)
    protected String annofiscalei;
    @XmlElement(name = "__SERIE_S")
    protected String series;
    @XmlElement(name = "__NUMERO_DOCUMENTO_L", required = true)
    protected String numerodocumentol;
    @XmlElement(name = "__CODICE_FISCALE_S", required = true)
    protected String codicefiscales;
    @XmlElement(name = "__PARTITA_IVA_S", required = true)
    protected String partitaivas;
    @XmlElement(name = "CODICE_CLIENTE", required = true)
    protected String codicecliente;
    @XmlElement(name = "__DENOMINAZIONE_S", required = true)
    protected String denominaziones;
    @XmlElement(name = "TOTALE_IMPORTO_D")
    protected String totaleimportod;
    @XmlElement(name = "NUMERO_DOC_RIF", required = true)
    protected String numerodocrif;
    @XmlElement(name = "FILE_ID", required = true)
    protected String fileid;
    @XmlElement(name = "LOT_ID", required = true)
    protected String lotid;
    @XmlElement(name = "DOC_HASH", required = true)
    protected String dochash;
    @XmlElement(name = "FILE_NAME", required = true)
    protected String filename;

    /**
     * Gets the value of the datadocumentodt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATADOCUMENTODT() {
        return datadocumentodt;
    }

    /**
     * Sets the value of the datadocumentodt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATADOCUMENTODT(String value) {
        this.datadocumentodt = value;
    }

    /**
     * Gets the value of the dataregistrazione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATAREGISTRAZIONE() {
        return dataregistrazione;
    }

    /**
     * Sets the value of the dataregistrazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATAREGISTRAZIONE(String value) {
        this.dataregistrazione = value;
    }

    /**
     * Gets the value of the datainizionumerazionedt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDATAINIZIONUMERAZIONEDT() {
        return datainizionumerazionedt;
    }

    /**
     * Sets the value of the datainizionumerazionedt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDATAINIZIONUMERAZIONEDT(String value) {
        this.datainizionumerazionedt = value;
    }

    /**
     * Gets the value of the annofiscalei property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANNOFISCALEI() {
        return annofiscalei;
    }

    /**
     * Sets the value of the annofiscalei property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANNOFISCALEI(String value) {
        this.annofiscalei = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERIES() {
        return series;
    }

    /**
     * Sets the value of the series property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERIES(String value) {
        this.series = value;
    }

    /**
     * Gets the value of the numerodocumentol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMERODOCUMENTOL() {
        return numerodocumentol;
    }

    /**
     * Sets the value of the numerodocumentol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMERODOCUMENTOL(String value) {
        this.numerodocumentol = value;
    }

    /**
     * Gets the value of the codicefiscales property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODICEFISCALES() {
        return codicefiscales;
    }

    /**
     * Sets the value of the codicefiscales property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODICEFISCALES(String value) {
        this.codicefiscales = value;
    }

    /**
     * Gets the value of the partitaivas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTITAIVAS() {
        return partitaivas;
    }

    /**
     * Sets the value of the partitaivas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTITAIVAS(String value) {
        this.partitaivas = value;
    }

    /**
     * Gets the value of the codicecliente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCODICECLIENTE() {
        return codicecliente;
    }

    /**
     * Sets the value of the codicecliente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCODICECLIENTE(String value) {
        this.codicecliente = value;
    }

    /**
     * Gets the value of the denominaziones property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDENOMINAZIONES() {
        return denominaziones;
    }

    /**
     * Sets the value of the denominaziones property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDENOMINAZIONES(String value) {
        this.denominaziones = value;
    }

    /**
     * Gets the value of the totaleimportod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTOTALEIMPORTOD() {
        return totaleimportod;
    }

    /**
     * Sets the value of the totaleimportod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTOTALEIMPORTOD(String value) {
        this.totaleimportod = value;
    }

    /**
     * Gets the value of the numerodocrif property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNUMERODOCRIF() {
        return numerodocrif;
    }

    /**
     * Sets the value of the numerodocrif property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNUMERODOCRIF(String value) {
        this.numerodocrif = value;
    }

    /**
     * Gets the value of the fileid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILEID() {
        return fileid;
    }

    /**
     * Sets the value of the fileid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILEID(String value) {
        this.fileid = value;
    }

    /**
     * Gets the value of the lotid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLOTID() {
        return lotid;
    }

    /**
     * Sets the value of the lotid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLOTID(String value) {
        this.lotid = value;
    }

    /**
     * Gets the value of the dochash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDOCHASH() {
        return dochash;
    }

    /**
     * Sets the value of the dochash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDOCHASH(String value) {
        this.dochash = value;
    }

    /**
     * Gets the value of the filename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFILENAME() {
        return filename;
    }

    /**
     * Sets the value of the filename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFILENAME(String value) {
        this.filename = value;
    }

}
