//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.11 at 03:45:14 PM CEST 
//


package com.mycompany.camel.xml.savefatture;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TESTATA"/>
 *         &lt;element ref="{}DOCUMENTI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "testata",
    "documenti"
})
@XmlRootElement(name = "ROOT")
public class ROOT {

    @XmlElement(name = "TESTATA", required = true)
    protected TESTATA testata;
    @XmlElement(name = "DOCUMENTI", required = true)
    protected DOCUMENTI documenti;

    /**
     * Gets the value of the testata property.
     * 
     * @return
     *     possible object is
     *     {@link TESTATA }
     *     
     */
    public TESTATA getTESTATA() {
        return testata;
    }

    /**
     * Sets the value of the testata property.
     * 
     * @param value
     *     allowed object is
     *     {@link TESTATA }
     *     
     */
    public void setTESTATA(TESTATA value) {
        this.testata = value;
    }

    /**
     * Gets the value of the documenti property.
     * 
     * @return
     *     possible object is
     *     {@link DOCUMENTI }
     *     
     */
    public DOCUMENTI getDOCUMENTI() {
        return documenti;
    }

    /**
     * Sets the value of the documenti property.
     * 
     * @param value
     *     allowed object is
     *     {@link DOCUMENTI }
     *     
     */
    public void setDOCUMENTI(DOCUMENTI value) {
        this.documenti = value;
    }

}
